# Generated by Django 5.2.4 on 2025-07-14 03:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الفئة')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('icon', models.CharField(default='fas fa-building', max_length=50, verbose_name='الأيقونة')),
            ],
            options={
                'verbose_name': 'فئة القاعة',
                'verbose_name_plural': 'فئات القاعات',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='الاسم')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('subject', models.CharField(max_length=200, verbose_name='الموضوع')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإرسال')),
                ('is_read', models.BooleanField(default=False, verbose_name='مقروءة')),
            ],
            options={
                'verbose_name': 'رسالة تواصل',
                'verbose_name_plural': 'رسائل التواصل',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم القاعة')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('capacity', models.PositiveIntegerField(verbose_name='السعة')),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر للساعة')),
                ('image', models.ImageField(upload_to='halls/', verbose_name='الصورة')),
                ('status', models.CharField(choices=[('available', 'متاح'), ('maintenance', 'صيانة'), ('booked', 'محجوز')], default='available', max_length=20, verbose_name='الحالة')),
                ('features', models.JSONField(default=list, verbose_name='المميزات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hall_booking.category', verbose_name='الفئة')),
            ],
            options={
                'verbose_name': 'قاعة',
                'verbose_name_plural': 'القاعات',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='رقم الحجز')),
                ('customer_name', models.CharField(max_length=200, verbose_name='اسم العميل')),
                ('customer_email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('event_title', models.CharField(max_length=200, verbose_name='عنوان الحدث')),
                ('event_description', models.TextField(verbose_name='وصف الحدث')),
                ('start_datetime', models.DateTimeField(verbose_name='تاريخ ووقت البداية')),
                ('end_datetime', models.DateTimeField(verbose_name='تاريخ ووقت النهاية')),
                ('attendees_count', models.PositiveIntegerField(verbose_name='عدد الحضور')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر الإجمالي')),
                ('status', models.CharField(choices=[('pending', 'في الانتظار'), ('approved', 'موافق عليه'), ('rejected', 'مرفوض'), ('cancelled', 'ملغي'), ('completed', 'مكتمل')], default='pending', max_length=20, verbose_name='الحالة')),
                ('admin_notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات الإدارة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الطلب')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hall_booking.hall', verbose_name='القاعة')),
            ],
            options={
                'verbose_name': 'حجز',
                'verbose_name_plural': 'الحجوزات',
                'ordering': ['-created_at'],
            },
        ),
    ]
