# Generated by Django 5.2.4 on 2025-07-14 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall_booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HallImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='halls/gallery/', verbose_name='صورة إضافية')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرفع')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='hall_booking.hall', verbose_name='القاعة')),
            ],
            options={
                'verbose_name': 'صورة قاعة',
                'verbose_name_plural': 'صور القاعات',
            },
        ),
    ]
